<?php

namespace Ephp\StatsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VisitaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitaRepository extends EntityRepository
{
}
