<?php

namespace Ephp\StatsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VisitaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitaRepository extends EntityRepository {

    public function last($area, $n = 10) {
        return $this->createQueryBuilder('v')
                ->leftJoin('v.aree', 'a')
                ->where('a.area = :area')
                ->setParameter('area', $area)
                ->orderBy('v.open_at', 'DESC')
                ->setMaxResults($n)
                ->getQuery()
                ->execute();
        ;
    }

}
